### ISSUE TITLE
BIN file size optimization

### ISSUE THREAD

**Issue by SandeepanSengupta** [watterott/SAM-BAR#1]
When compiled from .atsln, the binary file generating is ~19KB. But it's supposed to be ~16KB (15.3KB) as your precompiled binaries are having that size. How to compress file size

**Comment by awatterott** [comment]
Do you have made a "release" build? Because with debugging information the size will be over 16KB.

**Comment by SandeepanSengupta** [comment]
Oh! My bad. Sorry.
Few more things,
1) How to increase UDI_MSC_GLOBAL_VENDOR_ID charecter length in conf_usb.h
2) Why FAT_CHECKSUM() in Virtual_FAT.c is not having '.' (as in NAME.extension vs NAMEextension)

**Comment by awatterott** [comment]
1. It is fixed to 8 characters and cannot be changed.
2. This is the MSDOS 8.3 FAT file naming. The point is not saved in the FAT table.
