### ISSUE TITLE
Boot load pin

### ISSUE THREAD

**Issue by FriedCircuits** [watterott/SAM-BAR#2]
Hi, 
Is there enough room to add support back in for the boot load pin?  PA15. 

Thanks

**Comment by awatterott** [comment]
Yes, that is possible.
Currently the bootloader can be started with a double reset and this needs no extra pin. Why do you want to add a boot pin?

**Comment by FriedCircuits** [comment]
I am going to be using a custom board that does not have a reset button. Also I tired the double reset on the official arduino zero and it never worked. 

Thanks.

**Comment by awatterott** [comment]
We have not seen any problems yet. There are alse different ways to start the bootloader:
* double reset within 0.5s
* user program writes magic data to RAM and does a soft-reset
* user program erases the first flash page and does a soft-reset ([Arduino uses this](https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/Reset.cpp#L41))

**Comment by FriedCircuits** [comment]
I was able to add in the code for the boot pin. At least it will be an option and I can remove it if I end up not needing it but it is a good backup. Now if I can just fix the other problem.

**Comment by awatterott** [comment]
You only need a driver for the serial port (VCP) and to generate the catalog file a code signing certificate is needed. Here is a good guide from David Grayson: http://www.davidegrayson.com/signing/
