### ISSUE TITLE
Feature request: File access from sketch

### ISSUE THREAD

**Issue by scswift** [watterott/SAM-BAR#4]
This bootloader is excellent, but what would make it even better would be if it were possible to upload and access any file you want.

For example, if a user needs to configure a board but can't recompile the sketch, you could allow them to upload a text file with configuration data, and with a flash FAT library you provide, that configuration file could be accessed from within the sketch!

**Comment by awatterott** [comment]
I think that will make the bootloader much bigger. If you want such a feature then you can also do this in the sketch/user application.

**Comment by scswift** [comment]
I haven't used this bootloader myself yet, so forgive my ignorance, but if you can't drag and drop random files on there already, what happens when a user attempts to?

In case I was unclear, the helper functions I was suggesting to allow you to access these files would be a supplementary library included in the sketch. The only thing the bootloader itself would need to do is allow for any file to be placed on the device.

**Comment by awatterott** [comment]
There can be only one binary file and this will be stored in the flash memory of the controller.
