### ISSUE TITLE
Porting to SAMD11C14

### ISSUE THREAD

**Issue by SandeepanSengupta** [watterott/SAM-BAR#5]
Is it possible to port **MSD-CDC _composite_ bootloader** to **[this](https://github.com/mattairtech/ArduinoCore-samd/tree/master/variants/Generic_D11C14A)** system. Also, support FATFS for attatched MicroSD will be great.

**Comment by awatterott** [comment]
Yes, I think that should be no problem. We have not planned to add microSD support to the bootloader.

**Comment by SandeepanSengupta** [comment]
Thank you for replying and looking into this matter.
The thing is I'm a newbie in ARM and do not have the skillset to pull this
idea on my own. I'm only experienced in Arduino and Eagle.

And about that microSD support, I'm a bit confused, it appeares that there
is a FATFS library for arduino, however I'm not sure if it is compatible
with SAMD11C14 (as ported by Justin Mattair)
As far I know, you two are the only people working on it (MSD/CDC
bootloader).

So, I have another request,
Can you point me some library that will bring FATFS to ATSAMD11C14

Regards

On Thu, Nov 16, 2017 at 7:42 PM, Andreas Watterott <notifications@github.com

**Comment by awatterott** [comment]
You can use the standard Arduino "SD" library for interfacing a SD card with FAT16/FAT32. It will work with all Arduino compatible MCUs.
