### ISSUE TITLE
Serial port not showing

### ISSUE THREAD

**Issue by sanotronics** [watterott/SAM-BAR#7]
hello!

I want to use this to make a custom SAMD21 board.

I am making tests with the SparkFun SAMD21 Dev breakout board.

As soon as I flash the bootloader with the SAM-ICE programmer using Atmel Studio, the MSC device shows up with a FLASH.bin file.

I replace this file with the one I compile from the Arduino IDE (sketch is working already).
To compile I select **Arduino Zero (Native USB)** as the board.

Nothing happens then. The code doesn't run, and the USB-Serial COM port does not show up.

I am using Windows 10. I noticed there are some drivers on the "arduino" folder, but my computer does not even detect a device to install the drivers for.

Is there a procedure explained somewhere to use this bootloader?

Thanks for your help!
Franco.

**Comment by awatterott** [comment]
SAM-BAR is 16k big and so you will need other [linker settings](https://github.com/watterott/SAM-BAR/blob/master/arduino/sambar/samd/variants/arduino_zero/linker_scripts/gcc/flash_with_bootloader.ld#L28).
I would recommend the [UF2 Bootloader](https://github.com/awatterott/uf2-samd21), which is 8k big and we have added support for binary files to it.
